---
- hosts: all
  sudo: true
  pre_tasks:
   - name: update apt cache
     apt: update_cache=yes
  tasks:
   - name: install required packages
     apt: name={{ item }} state=present
     with_items:
        - git
        - e
